package projekt;

/**
 * Główna klasa programu
 * @author Heniek
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        OknoPomocnicze = new javax.swing.JPanel();
        WspolLabel = new javax.swing.JLabel();
        StopienLabel = new javax.swing.JLabel();
        StopienText = new javax.swing.JTextField();
        WspolText = new javax.swing.JTextField();
        ZatwierdzW = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ZakresW = new javax.swing.JTextField();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ZatwierdzE = new javax.swing.JButton();
        ExpABC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ZakresE = new javax.swing.JTextField();
        jFrame3 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ZakresM = new javax.swing.JTextField();
        Metoda_siecznych = new javax.swing.JButton();
        Metoda_stycznych = new javax.swing.JButton();
        Wynik = new javax.swing.JLabel();
        liczbaIteracji = new javax.swing.JLabel();
        OknoWyjatku = new javax.swing.JFrame();

        jPanel3 = new javax.swing.JPanel();
        TekstWyjatku = new javax.swing.JLabel();
        OknoGlowne = new javax.swing.JPanel();
        naglowek = new javax.swing.JLabel();
        wybFunkcje = new javax.swing.JLabel();
        Button_Wielomian = new javax.swing.JButton();
        Button_Ekspotencjalna = new javax.swing.JButton();
        WzorWielomian = new javax.swing.JLabel();
        WzorExp = new javax.swing.JLabel();

        WspolLabel.setText("<html>Podaj współczynniki zaczynając od tego przy najwyższej potędze (jeden więcej niż wynosi stopień, oddzielone średnikami)</html>");

        StopienLabel.setText("<html>Podaj stopień wielomianu</html>");

        ZatwierdzW.setText("Zatwierdź");
        ZatwierdzW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZatwierdzWActionPerformed1(evt);
            }
        });

        jLabel2.setText("<html>Podaj zakres w jakim ma być wyrysowany wykres (oddzielony średnikiem)</html>");

        javax.swing.GroupLayout OknoPomocniczeLayout = new javax.swing.GroupLayout(OknoPomocnicze);
        OknoPomocnicze.setLayout(OknoPomocniczeLayout);
        OknoPomocniczeLayout.setHorizontalGroup(
            OknoPomocniczeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OknoPomocniczeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OknoPomocniczeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OknoPomocniczeLayout.createSequentialGroup()
                        .addComponent(StopienLabel)
                        .addContainerGap())
                    .addGroup(OknoPomocniczeLayout.createSequentialGroup()
                        .addGroup(OknoPomocniczeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StopienText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WspolText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(OknoPomocniczeLayout.createSequentialGroup()
                        .addGroup(OknoPomocniczeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZakresW, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZatwierdzW))
                        .addGap(0, 159, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OknoPomocniczeLayout.createSequentialGroup()
                        .addGroup(OknoPomocniczeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(WspolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addGap(28, 28, 28))))
        );
        OknoPomocniczeLayout.setVerticalGroup(
            OknoPomocniczeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OknoPomocniczeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StopienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StopienText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WspolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WspolText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ZakresW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ZatwierdzW)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OknoPomocnicze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OknoPomocnicze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setText("<html>Podaj współczynniki a, b, c (oddzielone średnikami)</html>");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 14));

        ZatwierdzE.setText("Zatwierdź");
        ZatwierdzE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZatwierdzEActionPerformed(evt);
            }
        });

        jLabel3.setText("<html>Podaj zakres w jakim ma być wyrysowany wykres (oddzielony średnikiem)</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZatwierdzE)
                            .addComponent(ExpABC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZakresE, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExpABC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ZakresE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ZatwierdzE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setText("<html>Podaj zakres w którym ma być szukane miejsce zerowe (metoda siecznych) lub przybliżone miejsce zerowe (metoda stycznych)</html>");

        Metoda_siecznych.setText("Metoda siecznych");
        Metoda_siecznych.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Metoda_siecznychActionPerformed(evt);
            }
        });

        Metoda_stycznych.setText("Metoda stycznych");
        Metoda_stycznych.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Metoda_stycznychActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(liczbaIteracji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Wynik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Metoda_siecznych, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(Metoda_stycznych, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ZakresM, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ZakresM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Metoda_siecznych)
                    .addComponent(Metoda_stycznych))
                .addGap(18, 18, 18)
                .addComponent(Wynik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(liczbaIteracji, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        OknoWyjatku.setSize(new java.awt.Dimension(300, 140));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TekstWyjatku, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TekstWyjatku, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout OknoWyjatkuLayout = new javax.swing.GroupLayout(OknoWyjatku.getContentPane());
        OknoWyjatku.getContentPane().setLayout(OknoWyjatkuLayout);
        OknoWyjatkuLayout.setHorizontalGroup(
            OknoWyjatkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OknoWyjatkuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        OknoWyjatkuLayout.setVerticalGroup(
            OknoWyjatkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OknoWyjatkuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        OknoWyjatku.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        naglowek.setText("<html>Program do wyznaczania miejsca zerowego fukcji metodą stycznych lub siecznych</html>");

        wybFunkcje.setText("Wybierz funkcję");

        Button_Wielomian.setText("Wielomian");
        Button_Wielomian.setFocusable(false);
        Button_Wielomian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Wielomian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_Wielomian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_WielomianActionPerformed(evt);
            }
        });

        Button_Ekspotencjalna.setText("Eksponencjalna");
        Button_Ekspotencjalna.setFocusable(false);
        Button_Ekspotencjalna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EkspotencjalnaActionPerformed(evt);
            }
        });

        WzorWielomian.setText("<html>\na<sub>1</sub>*x<sup>n</sup>+a<sub>2</sub>*x<sup>n-1</sup>+...+a<sub>i</sub>\n</html>");

        WzorExp.setText("<html> a*<b>e</b><sup>b*x</sup>*sin(c*x) </html>");

        javax.swing.GroupLayout OknoGlowneLayout = new javax.swing.GroupLayout(OknoGlowne);
        OknoGlowne.setLayout(OknoGlowneLayout);
        OknoGlowneLayout.setHorizontalGroup(
            OknoGlowneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OknoGlowneLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(wybFunkcje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OknoGlowneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OknoGlowneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(OknoGlowneLayout.createSequentialGroup()
                        .addGroup(OknoGlowneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Button_Wielomian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Ekspotencjalna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OknoGlowneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WzorWielomian)
                            .addComponent(WzorExp)))
                    .addComponent(naglowek, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        OknoGlowneLayout.setVerticalGroup(
            OknoGlowneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OknoGlowneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(naglowek, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wybFunkcje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OknoGlowneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OknoGlowneLayout.createSequentialGroup()
                        .addComponent(Button_Wielomian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE))
                    .addGroup(OknoGlowneLayout.createSequentialGroup()
                        .addComponent(WzorWielomian)
                        .addGap(13, 13, 13)))
                .addGroup(OknoGlowneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_Ekspotencjalna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WzorExp))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OknoGlowne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OknoGlowne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_WielomianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_WielomianActionPerformed
        jFrame1.setVisible(true);
        jFrame1.setSize(350,350);
        jFrame1.setLocationRelativeTo(null);
        Metoda.funkcja=0;
    }//GEN-LAST:event_Button_WielomianActionPerformed

    private void ZatwierdzWActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZatwierdzWActionPerformed
        try{
            while(true){
                if(Integer.parseInt(Menu.StopienText.getText())<0){
                    OknoWyjatku.setVisible(true);
                    TekstWyjatku.setText("Stopień wielomianu musi być większy od 0");
                    break;
            }
             Wielomian.pobierzWartosci();
             Wykres.pobierzZakres();
             Wykres.run();
             jFrame3.setVisible(true);
             jFrame3.setSize(350,300);
             jFrame3.setLocationRelativeTo(null);
             break;
            }
    }
    catch(IndexOutOfBoundsException i){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wpisano niewłaściwą ilość danych");
    }
    catch(NumberFormatException n){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wystąpił błąd związany z formatem danych");
    }
    catch(Exception e){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wystąpił nieznany błąd");
    }
        jFrame1.setVisible(false);
    }//GEN-LAST:event_ZatwierdzWActionPerformed
    private void Button_EkspotencjalnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EkspotencjalnaActionPerformed
        jFrame2.setVisible(true);
        jFrame2.setSize(350,300);
        jFrame2.setLocationRelativeTo(null);
        Metoda.funkcja=1;
    }//GEN-LAST:event_Button_EkspotencjalnaActionPerformed

    private void ZatwierdzEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZatwierdzEActionPerformed
    try{
        jFrame2.setVisible(false);
        Exp.pobierzWartości();
        Wykres.pobierzZakres();
        Wykres.run();
        jFrame3.setVisible(true);
        jFrame3.setSize(350,300);
        jFrame3.setLocationRelativeTo(null);
    }
    catch(IndexOutOfBoundsException i){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wpisano niewłaściwą ilość danych");
    }
    catch(NumberFormatException n){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wystąpił błąd związany z formatem danych");
    }
    catch(Exception e){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wystąpił nieznany błąd");
    }
    }//GEN-LAST:event_ZatwierdzEActionPerformed

    private void ZatwierdzWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZatwierdzWActionPerformed1
    }//GEN-LAST:event_ZatwierdzWActionPerformed1

    private void Metoda_siecznychActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Metoda_siecznychActionPerformed
    try{
        Metoda.pobierzPunkty();
        Wynik.setText("Miejsce zerowe x0= "+Metoda.siecznych(Metoda.funkcja));
        liczbaIteracji.setText("Liczba iteracji= "+Metoda.liczbaIteracji());
    }
    catch(IndexOutOfBoundsException i){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wpisano niewłaściwą ilość danych");
    }
    catch(NumberFormatException n){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wystąpił błąd związany z formatem danych");
    }
    catch(Exception e){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wystąpił nieznany błąd");
    }
    }//GEN-LAST:event_Metoda_siecznychActionPerformed

    private void Metoda_stycznychActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Metoda_stycznychActionPerformed
    try{
        Metoda.pobierzPunkty();
        Wynik.setText("Miejsce zerowe x0= "+Metoda.stycznych(Metoda.funkcja));
        liczbaIteracji.setText("Liczba iteracji= "+Metoda.liczbaIteracji());
    }
    catch(IndexOutOfBoundsException i){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wpisano niewłaściwą ilość danych");
    }
    catch(NumberFormatException n){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wystąpił błąd związany z formatem danych");
    }
    catch(Exception e){
        OknoWyjatku.setVisible(true);
        TekstWyjatku.setText("Wystąpił nieznany błąd");
    }
    }//GEN-LAST:event_Metoda_stycznychActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Ekspotencjalna;
    private javax.swing.JButton Button_Wielomian;
    protected static javax.swing.JTextField ExpABC;
    private javax.swing.JButton Metoda_siecznych;
    private javax.swing.JButton Metoda_stycznych;
    private javax.swing.JPanel OknoGlowne;
    private javax.swing.JPanel OknoPomocnicze;
    private javax.swing.JFrame OknoWyjatku;
    private javax.swing.JLabel StopienLabel;
    protected static javax.swing.JTextField StopienText;
    private javax.swing.JLabel TekstWyjatku;
    private javax.swing.JLabel WspolLabel;
    protected static javax.swing.JTextField WspolText;
    private javax.swing.JLabel Wynik;
    private javax.swing.JLabel WzorExp;
    private javax.swing.JLabel WzorWielomian;
    protected static javax.swing.JTextField ZakresE;
    protected static javax.swing.JTextField ZakresM;
    protected static javax.swing.JTextField ZakresW;
    private javax.swing.JButton ZatwierdzE;
    private javax.swing.JButton ZatwierdzW;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel liczbaIteracji;
    private javax.swing.JLabel naglowek;
    private javax.swing.JLabel wybFunkcje;
    // End of variables declaration//GEN-END:variables
}
